name: CI

on:
  push:
    branches: [ "*" ]  # Triggers on push to any branch
  pull_request:
    branches: [ "*" ]  # Triggers on PR to any branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
